version: '3'

volumes:
  db:
    driver: local


services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    ports:
      - 8080:8080 # Listen to HTTP on host port 80 and forward to keycloak on 8080
      - 8443:8443 # Listen to HTTPS on host port 443 and forward to keycloak on 8443

    environment:
      - KEYCLOAK_ADMIN_USER=admin # Change the username!
      - KEYCLOAK_ADMIN=admin
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
      - KEYCLOAK_ADMIN_PASSWORD=${KC_PASS}
    command:
      - start-dev # Start Keycloak in developer mode
