version: "3"

volumes:
  postgres-kc-db:
    driver: local
  postgres-be-db:
    driver: local
  pgadmin-data:
    driver: local

services:
  be-postgres:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres-be-db:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: site
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASS}

  kc-postgres:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres-kc-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASS}

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # KC_LOG_LEVEL: debug
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KC_PASS}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://kc-postgres:5432/keycloak
      KC_DB_SCHEMA: public
      KC_DB_PASSWORD: ${DB_PASS}
      KC_DB_USERNAME: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
    depends_on:
      - kc-postgres
    command:
      - start-dev

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - be-postgres
      - kc-postgres
