version: '3'

volumes:
  db:
    driver: local


services:
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./:/etc/nginx/conf.d
      - /site-frontend/build:/usr/share/site-frontend
      # - /home/sam/site-frontend/dist/site-frontend:/usr/share/site-frontend
    network_mode: "host"

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DB_PASS:?db password required}
    ports:
      - 5434:5434
    volumes: 
      - db:/var/lib/postgresql/data


  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    ports:
      - 8080:8080 # Listen to HTTP on host port 80 and forward to keycloak on 8080
      - 8443:8443 # Listen to HTTPS on host port 443 and forward to keycloak on 8443

    volumes:
      - "./certs/fullchain.pem:/etc/x509/https/tls.crt" # Map certificate to container
      - "./certs/privkey.pem:/etc/x509/https/tls.key" # Map private key to container

    environment:
      #- JAVA_OPTS_APPEND="-D keycloak.profile.feature.upload_script=enabled"
      - KEYCLOAK_ADMIN_USER=admin # Change the username!
      - KC_HOSTNAME=keycloak.sam-sla.net
      - KC_HOSTNAME_PORT=443
      - KC_HTTPS_CERTIFICATE_FILE=/etc/x509/https/tls.crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/x509/https/tls.key
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${KC_PASS}
    command:
      - start # Start Keycloak in developer mode
