version: '3.4'
services:
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "4000:4000"
    network_mode: "host"

  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    environment:
      - AUDIOBOOKSHELF_UID=99
      - AUDIOBOOKSHELF_GID=100
    ports:
      - 13378:80
    volumes:
      - ~/shelf/audiobooks:/audiobooks
      - ~/shelf/config:/config
      - ~/shelf/metadata:/metadata
    
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: "host"
    volumes:
      - ~/jelly/config:/config
      - ~/jelly/cache:/cache
      - ~/jelly/media:/media
    restart: "unless-stopped"

  nextcloud:
    container_name: nextcloud
    restart: unless-stopped
    image: nextcloud
    ports:
      - 8080:80 #Port change
    volumes:
      - /containers/cloud/nextcloud/apps:/var/www/html/apps
      - /containers/cloud/nextcloud/config:/var/www/html/config
      - /containers/cloud/nextcloud/data:/var/www/html/data
    depends_on:
      - db

  db:
    container_name: maria-db
    restart: unless-stopped
    image: mariadb
    command: --innodb-read-only-compressed=OFF #Maria-DB fix
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}}
      MYSQL_DATABASE: ncdb
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /containers/cloud/mariadb:/var/lib/mysql
