version: '3.4'
services:
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "4000:4000"
    network_mode: "host"

  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    environment:
      - AUDIOBOOKSHELF_UID=99
      - AUDIOBOOKSHELF_GID=100
    ports:
      - 13378:80
    volumes:
      - ~/shelf/audiobooks:/audiobooks
      - ~/shelf/config:/config
      - ~/shelf/metadata:/metadata
    
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: "host"
    volumes:
      - ~/jelly/config:/config
      - ~/jelly/cache:/cache
      - ~/jelly/media:/media
    restart: "unless-stopped"

  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=testing123
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    hostname: 'postgres' 
    volumes:
      - db:/var/lib/postgres
    environment:
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testing123
  

volumes:
  nextcloud:
  db: