version: '3.4'
services:
  nginx:
    image: nginx:mainline-alpine
    container_name: site.nginx
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "4000:4000"
    network_mode: "host"
