global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["172.17.0.1:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["172.17.0.1:9100"]

  - job_name: "grafana"
    static_configs:
    - targets: ["172.17.0.1:3001"]
  
  - job_name: "frontend"
    scrape_interval: 10s
    static_configs:
    - targets: ["172.17.0.1:3000"]
  
  - job_name: "backend"
    scrape_interval: 10s
    static_configs:
    - targets: ["172.17.0.1:5000"]