apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: site
resources:
  - namespace.yaml
  - configmap-nginx.yaml
  - configmap-keycloak-theme.yaml
  - postgres-be.yaml
  - postgres-kc.yaml
  - keycloak.yaml
  - redis.yaml
  - kafka.yaml
  - prometheus-monitoring.yaml
  - nginx.yaml
  - poddisruptionbudgets.yaml
  - ingress.yaml
