apiVersion: v1
kind: Secret
metadata:
  name: site-secrets
  namespace: site
type: Opaque
stringData:
  DB_PASS: "change-me-db-password"
  KC_PASS: "change-me-keycloak-admin-password"
  POSTGRES_USER: "admin"
  REDIS_PASSWORD: "change-me-redis-password"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.site.svc.cluster.local:9092"
